PORTNAME=	pius-netmap
PORTVERSION=	0.2
CATEGORIES=	net
MASTER_SITES=	# empty

MAINTAINER=	msk@petabi.com
COMMENT=	Utilities to access netmap buffer

USE_BZIP2=	yes
USES=		cmake

.include <bsd.port.mk>
