PORTNAME=	regorus-sdk
PORTVERSION=	0.1
CATEGORIES=	net
MASTER_SITES=	# empty

MAINTAINER=	kwanghyunk@petabi.com
COMMENT=	Software development kit for REgorus

BUILD_DEPENDS+=	atf>=0.21:${PORTSDIR}/devel/atf

USE_BZIP2=	yes
USES=		cmake

CFLAGS+=	-DNDEBUG

.include <bsd.port.mk>
