PORTNAME=	trafficgen
PORTVERSION=	1.0.2
CATEGORIES=	net
MASTER_SITES=	# empty

MAINTAINER=	mshao@petabi.com
COMMENT=	Traffic generator

USE_BZIP2=	yes
USES=		cmake

CFLAGS+=	-DNDEBUG

.include <bsd.port.mk>
