PORTNAME=	pius-arp
PORTVERSION=	1.0
CATEGORIES=	net
MASTER_SITES=	# empty

MAINTAINER=	msk@petabi.com
COMMENT=	ARP and NDP for PIUS

USE_BZIP2=	yes
USES=		cmake

MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
