PORTNAME=	sniffles
PORTVERSION=	1.3.1
CATEGORIES=	net python
MASTER_SITES=	# empty

MAINTAINER=	vvalgenti@petabi.com
COMMENT=	Packet capture generator for IDS evaluation

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}remerge>=0.9:${PORTSDIR}/devel/py-remerge

USE_PYTHON=		3
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
