PORTNAME=	sniffles
PORTVERSION=	3.3.1
CATEGORIES=	net python
MASTER_SITES=	# empty

MAINTAINER=	vvalgenti@petabi.com
COMMENT=	Packet capture generator for IDS evaluation

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}sortedcontainers>=0.9.5:${PORTSDIR}/devel/py3-sortedcontainers

USES=		python:3
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
