PORTNAME=	sniffles
PORTVERSION=	3.0.0
CATEGORIES=	net python
MASTER_SITES=	# empty

MAINTAINER=	vvalgenti@petabi.com
COMMENT=	Packet capture generator for IDS evaluation

USES=		python:3
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
