# Created by: antoine@FreeBSD.org
# $FreeBSD: branches/2015Q2/devel/py-sortedcontainers/Makefile 382402 2015-03-27 13:12:29Z antoine $

PORTNAME=	sortedcontainers
PORTVERSION=	0.9.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Python Sorted Container Types: SortedList, SortedDict, and SortedSet

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
